In [4]:
import os
import cv2
import numpy as np
folder_paths = ['dataset/rock/', 'dataset/paper/', 'dataset/scissors/']
files = []
for folder in folder_paths:
    for file in os.listdir(folder):
        full_path = os.path.join(folder, file)
        if ".DS_Store" not in full_path:
            files.append(full_path)

In [9]:
from keras.preprocessing import image
from keras.preprocessing.image import img_to_array
import pandas as pd
flattened_data = []
label = []
for x in files:
    img = cv2.imread(x,0)
    resized = cv2.resize(img, (50,50))
    img_arr = img_to_array(resized)
    img_arr /= 255
    flattened = img_arr.flatten().reshape(-1,50*50)
    if "rock" in x:
        label = np.append(flattened, 1)
        flattened_data.append(label)
    if "paper" in x:
        label = np.append(flattened, 0)
        flattened_data.append(label)
    if "scissors" in x:
        label = np.append(flattened, 2)
        flattened_data.append(label)
    
len(flattened_data)
data = pd.DataFrame(list(map(np.ravel, flattened_data)))
data = data.astype(int)
data = data.rename(columns={x:y for x,y in zip(data.columns,range(1,len(data.columns)+1))})
data.to_csv('dataset.csv', encoding='utf-8', index=False)

In [10]:
flattened_data

[array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 0., 0., 1.]),
 array([0., 0., 0., ..., 1., 1., 0.]),
 array([0., 0., 0., ..., 1., 1., 0.]),
 array([0., 0., 0., ..., 1., 1., 0.]),
 array([0., 0., 0., ..., 1., 1., 0.]),
 array([0., 0., 0., ..., 1., 1., 2.])]